### ISSUE TITLE
Visual issue with the small ProgressBar

### ISSUE THREAD

**Issue by quentinguidee** [nextcloud/nextcloud-vue#2569] opened 2022-03-23 09:48 UTC
In the small ProgressBar component (height = 4px), the blue line have an height of 6px instead of 4px. This causes a visual issue where we only see the top corner-radius.

**`size="small"` (4px)**
![image](https://user-images.githubusercontent.com/12123721/159670740-4cc3e228-5ed1-47fb-a5ad-f9ffd426c9b0.png)

**For comparison, `size="medium"` (6px)**
![image](https://user-images.githubusercontent.com/12123721/159670655-677f4fd5-9215-4c4d-94f3-e80e5b8a7852.png)

**Comment by Zackaria-Slimane** [comment] 2022-04-05 23:27
hello , if the issue is still present i would love to work on it if you could assign it to me !

**Comment by quentinguidee** [comment] 2022-04-05 23:42
> hello , if the issue is still present i would love to work on it if you could assign it to me !

Done ;)

**Closed** 2022-04-08 08:11 UTC
