### ISSUE TITLE
Cursor and hover state go crazy

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/nextcloud-vue#697] opened 2019-10-28 11:06 UTC
Have a component like:
```vue
			<ActionText
				:title="t('spreed', 'Chat notifications')">
```

Hover the item with the mouse and watch the cursor and hover state go crazy when you enter the text area

**Comment by raimund-schluessler** [comment] 2023-01-27 10:46
Cannot reproduce anymore. Closing.

**Closed by raimund-schluessler** 2023-01-27 10:46 UTC
Labels: bug, feature: actions
