### ISSUE TITLE
Plain emoji are replaced by emoji picker

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/nextcloud-vue#3846] opened 2023-03-02 09:01 UTC
I am kind of oldschool, thus I often write :-).
When I do this in NC26 beta, it is then replaced by first emoji entry when I press enter:

![image](https://user-images.githubusercontent.com/5836855/222381117-0fe4c869-d5e5-4618-89df-51496a88ed1e.png)

![image](https://user-images.githubusercontent.com/5836855/222381164-3afeac45-49cf-4b40-b600-95ab99830930.png)

So I know have to always type "some text :-) " to make sure that my oldschool emoji is not being replaced.

**Comment by tobiasKaminsky** [comment] 2023-03-02 09:02
GH emoji picker is doing it different: if :-) is not found in list, then it is being ignored.

**Comment by nickvergessen** [comment] 2023-03-02 09:58
You can use ESC or a space to stop it as far as I understood:
https://github.com/nextcloud/spreed/issues/8849

But yeah would be very glad if it would not collide 🫥

**Comment by tobiasKaminsky** [comment] 2023-03-02 11:50
ESC or space does not make any real difference, as I would still have to remember to press something else after typing an emoji.
It is "just" a better workaround :-) 

Btw: another solution would be to resolve ":-)" to :slightly_smiling_face:

**Comment by nickvergessen** [comment] 2023-03-02 11:54
> Btw: another solution would be to resolve ":-)" to :slightly_smiling_face:

-.- I heavily disagree there. I do the :P emojis intentionally

**Comment by tobiasKaminsky** [comment] 2023-03-02 14:53
Was just an idea, and nothing we need to do :)
WhatsApp Web is replacing it
Signal Desktop App not

**Comment by jancborchardt** [comment] 2023-03-16 05:19
Duplicate of https://github.com/nextcloud/nextcloud-vue/issues/3825 :) → closing in favor of that.

**Closed** 2023-03-16 05:19 UTC
