### ISSUE TITLE
Proposal: Add Prefix to all components

### ISSUE THREAD

**Issue by vinicius73** [nextcloud/nextcloud-vue#2960] opened 2022-08-05 21:40 UTC
We have some components like `Button` with native HTML elements. It should be avoided.
This is an [official recommendation](https://v2.vuejs.org/v2/style-guide/?redirect=true#Multi-word-component-names-essential).

A prefix like `NC` looks reasonable.

```html
<NCButton>FOO<NCButton/>
<nc-button>FOO<nc-button/>
```

This issue is related to #2959 this chance also turn ease see the difference between `components`, `directives`, and `functions`.

**Comment by raimund-schluessler** [comment] 2022-08-06 06:04
Duplicate of https://github.com/nextcloud/nextcloud-vue/issues/2643

**Closed** 2022-08-06 10:34 UTC
Labels: component, breaking, 0. to triage
