### ISSUE TITLE
NcListItem lost `a href` with update to 7.8.1+

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/nextcloud-vue#3921] opened 2023-03-23 19:54 UTC
This is actually a breaking change:
https://github.com/nextcloud/spreed/issues/9153

NcListItem entries like Talk's conversations in the left sidebar lost their `a href` and can therefore no longer be opened in a new tab with the mouse wheel, ctrl + click or right-click option, instead of the home page of talk or current conversation is loaded again with a trailing `#`

Before | After
---|---
[Bildschirmaufzeichnung vom 2023-03-23, 20-53-01.webm](https://user-images.githubusercontent.com/213943/227335649-f1f143ec-bf5e-40a0-8cfc-20b1f828bc32.webm) | [Bildschirmaufzeichnung vom 2023-03-23, 20-51-35.webm](https://user-images.githubusercontent.com/213943/227335418-23bdd261-b4eb-4e58-bf78-810e51999d8d.webm)

Is that fixable without a revert of #3775 ?

**Comment by nickvergessen** [comment] 2023-03-23 19:55
cc @raimund-schluessler @Chartman123 @ShGKme

**Comment by raimund-schluessler** [comment] 2023-03-23 20:01
That was not intended and I think it should be fixable without reverting. Could you maybe guide me to the place where this is used in Talk?

**Comment by nickvergessen** [comment] 2023-03-23 20:12
Install Talk master or stable26, and then hover entries in the left sidebar (as per before after videos?

**Comment by nickvergessen** [comment] 2023-03-23 20:12
(observe the target URL in the bottom left)

**Comment by ShGKme** [comment] 2023-03-23 20:14
Seems like the problem is here. It should use href in line 212 from RouterLink slotProps, not from component only props.

https://github.com/nextcloud/nextcloud-vue/blob/4690b32d23a451c8a67d711c8066b191008f2050/src/components/NcListItem/NcListItem.vue#L202-L212

**Comment by raimund-schluessler** [comment] 2023-03-23 20:15
> Install Talk master or stable26, and then hover entries in the left sidebar (as per before after videos?

I meant the code in Talk, I suppose it's this :slightly_smiling_face: 
https://github.com/nextcloud/spreed/blob/fc72eb92f50fd0983dd12e0498bd37063b453796/src/components/LeftSidebar/ConversationsList/Conversation.vue#L23-L33

**Comment by nickvergessen** [comment] 2023-03-23 20:16
Sorry, yes that's it

**Comment by ShGKme** [comment] 2023-03-23 20:19
Usage in the Talk is correct. It passes `to` prop as intended. The problem is that currently `NcListItem` ignores the link generated by RouterLink on `to` prop while setting `<a href`.

As the result the link is not correct, though it navigate by the click handler.

I can fix it, but in an hour...

**Comment by raimund-schluessler** [comment] 2023-03-23 20:19
> Seems like the problem is here. It should use href in line 212 from RouterLink slotProps, not from component only props.
> 
> https://github.com/nextcloud/nextcloud-vue/blob/4690b32d23a451c8a67d711c8066b191008f2050/src/components/NcListItem/NcListItem.vue#L202-L212

It wasn't like this before #3775 either. It always used the `href` prop. I am honestly a bit puzzled why talk ever showed a link there.

**Comment by ShGKme** [comment] 2023-03-23 20:21
> It wasn't like this before #3775 either. It always used the `href` prop. I am honestly a bit puzzled why talk ever showed a link there.

Because it is literally a link. It works as a link (it navigates), it renders as a link (`<a>` element).

**Comment by ShGKme** [comment] 2023-03-23 20:23
Anyway, `NcListItem` should not render a link that navigates not to its href.

**Comment by raimund-schluessler** [comment] 2023-03-23 20:24
But `router-link` rendered as a `li` and the `a` within got its `href` from the prop provided. How was the `href` of the `a` ever correct?

**Comment by ShGKme** [comment] 2023-03-23 20:38
> But `router-link` rendered as a `li` and the `a` within got its `href` from the prop provided. How was the `href` of the `a` ever correct?

`RounterLink` searches `a` elements in slot content:

https://github.com/vuejs/vue-router/blob/3d026ea14f8f8fd93da73889d2bcd2103d44bec7/src/components/link.js#L151-L180

**Comment by raimund-schluessler** [comment] 2023-03-23 20:42
> > But `router-link` rendered as a `li` and the `a` within got its `href` from the prop provided. How was the `href` of the `a` ever correct?
> 
> `RounterLink` searches `a` elements in slot content:
> 
> https://github.com/vuejs/vue-router/blob/3d026ea14f8f8fd93da73889d2bcd2103d44bec7/src/components/link.js#L151-L180

Ah, interesting I didn't know that. I am on a fix and currently test it with talk.

**Comment by raimund-schluessler** [comment] 2023-03-23 21:09
Fix is in #3922.

**Closed** 2023-03-24 13:40 UTC
Labels: bug, 1. to develop, feature: app-navigation, regression, feature: list-item
