### ISSUE TITLE
[Feature request] Make documentation available for previous versions

### ISSUE THREAD

**Issue by MarcelRobitaille** [nextcloud/nextcloud-vue#3374] opened 2022-10-17 22:36 UTC
Not all of us have upgraded beyond version 5.x.x. It would be nice to see documentation for our current version. Many documentation sites have a dropdown to select the version. A few off the top of my head: [pandas](https://pandas.pydata.org/docs/reference/index.html#api), [express](https://expressjs.com/en/4x/api.html), [Material UI](https://mui.com/material-ui/getting-started/overview/). I know this is a big request, but I think it would be very valuable for those of us who have not updated to 7.0.0 for whatever reason.

As a workaround, I considered cloning this project, checking out the tag of the version I'm on, and building the docs locally, but I don't see any documentation on how to do that. Does something like that exist?

**Comment by christianlupus** [comment] 2022-10-18 10:51
Duplicate of #3242. This one seems cleaner. Thus, I am closing the other one.

**Comment by MarcelRobitaille** [comment] 2022-10-18 11:10
Sorry @christianlupus, I couldn't find your issue in my search!

**Closed** 2023-06-27 08:40 UTC
