### ISSUE TITLE
Datepicker to narrow when show-week-numbers

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/nextcloud-vue#1014] opened 2020-04-10 20:05 UTC
The datepicker overflows when week-numbers are shown. Set `:show-week-numbers="true"` in the documentation to reproduce:

<img width="285" alt="Unbenannt" src="https://user-images.githubusercontent.com/2496460/79019643-1e6ce880-7b77-11ea-9efe-5f858a576ebb.png">

Happens in Calendar 2.0.3 now. @georgehrke @skjnldsv

**Comment by skjnldsv** [comment] 2020-04-10 20:22
Should be fixed already with https://github.com/nextcloud/nextcloud-vue/pull/995

**Comment by skjnldsv** [comment] 2020-04-10 20:23
https://github.com/nextcloud/nextcloud-vue/pull/995#issuecomment-610216841

**Comment by skjnldsv** [comment] 2020-04-10 20:23
Yep, perfect for me in https://nextcloud-vue-components.netlify.com/#/Components/DatetimePicker

![Capture d’écran_2020-04-10_22-23-34](https://user-images.githubusercontent.com/14975046/79020736-efa44180-7b79-11ea-8a9a-75bf53d13792.png)

**Comment by skjnldsv** [comment] 2020-04-10 20:24
Aaah, ok, I fixed it for `type="week"`, not `show-week-numbers`

**Comment by georgehrke** [comment] 2020-04-10 20:24
I updated to 1.5.0 before releasing 2.0.3

**Comment by skjnldsv** [comment] 2020-04-10 20:26
Well, I cannot reproduce with `show-week-numbers="true"` on the documentation, what template code are you using?

**Comment by georgehrke** [comment] 2020-04-10 20:27
https://github.com/nextcloud/calendar/blob/master/src/components/Shared/DatePicker.vue#L24

**Comment by georgehrke** [comment] 2020-04-10 20:28
> Well, I cannot reproduce with `show-week-numbers="true"` on the documentation, what template code are you using?

It's  `show-week-number="true"`, not  `show-week-numbers="true"`

**Comment by georgehrke** [comment] 2020-04-10 20:29
![DF83B60B-86FB-4DC4-8ED4-B5F0CF83C610](https://user-images.githubusercontent.com/1250540/79021001-b3251580-7b7a-11ea-818c-d10f4ccf7e3a.png)

**Comment by raimund-schluessler** [comment] 2020-08-03 19:57
Still an issue in the latest version, i.e. the Calendar app.

**Comment by raimund-schluessler** [comment] 2021-04-29 19:26
The problem is this line https://github.com/nextcloud/nextcloud-vue/blob/master/src/components/DatetimePicker/index.scss#L63 which doesn't take the week number column into account. But I don't know how to overwrite it, because there is no class indicating if the week numbers are shown. @skjnldsv Any idea? Maybe I am missing something.

**Comment by raimund-schluessler** [comment] 2021-04-29 19:51
I added a feature request to the datepicker library to have a class set when `show-week-number` is enabled: https://github.com/mengxiong10/vue2-datepicker/issues/600

**Comment by raimund-schluessler** [comment] 2021-05-04 12:33
Fix is in #1917. Adjustments to the datepicker library were not necessary.

**Closed** 2021-05-04 13:18 UTC
Labels: 1. to develop, bug, feature: datepicker
