### ISSUE TITLE
TextOverflow in Actions component

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/nextcloud-vue#1367] opened 2020-09-01 08:03 UTC
![image](https://user-images.githubusercontent.com/1250540/91823943-45b57680-ec3a-11ea-8d6c-59b44e08a4eb.jpeg)

Tested on v2.6.2

**Comment by georgehrke** [comment] 2020-09-01 08:07
![9B518FFD-AE82-4491-BB38-D8A96761B594](https://user-images.githubusercontent.com/1250540/91824386-f7ed3e00-ec3a-11ea-9738-a1ba24d8027f.png)

Only affects the title property, not the default slot

**Comment by skjnldsv** [comment] 2020-09-01 08:16
On the p, seems to work
```css
white-space: nowrap;
text-overflow: ellipsis;
overflow: hidden;
```

**Comment by raimund-schluessler** [comment] 2021-09-10 12:11
Cannot reproduce anymore, closing.

**Closed by raimund-schluessler** 2021-09-10 12:11 UTC
Labels: bug, 1. to develop
