### ISSUE TITLE
NcActionLink inside of NcActions is missing the target and rel attributes

### ISSUE THREAD

**Issue by HassoSigbjoernson** [nextcloud/nextcloud-vue#4236] opened 2023-06-20 08:40 UTC
**works as expected:**
```
<NcActionLink href="https://nextcloud.com" target="_blank">
	<template #icon>
		<OpenInNew :size="20" />
	</template>
</NcActionLink>
```

--> `<a data-v-1ba1edf1="" href="https://nextcloud.com" aria-label="" target="_blank" rel="nofollow noreferrer noopener" class="action-link focusable">...</a>`

**has no target or rel attribute:**
```
<NcActions>
	<NcActionLink href="https://nextcloud.com" target="_blank">
		<template #icon>
			<OpenInNew :size="20" />
		</template>
	</NcActionLink>
</NcActions>
```
--> `<a data-v-2e49be1e="" data-v-20a3e950="" data-v-8a67d7ee="" role="button" href="https://nextcloud.com" class="button-vue button-vue--icon-only button-vue--vue-tertiary action-item action-item--single">...</a>`

**Comment by raimund-schluessler** [comment] 2023-11-05 16:31
The `rel` attribute seems to be correctly present (now). `target` is not correctly set in `master`, but it is fixed in the vue 3 version in `next` branch.

**Comment by ShGKme** [comment] 2023-11-16 19:29
`target` works as expected in the current `@nextcloud/vue@8`.
`rel` is not supposed to be changeable.

If this is still an issue for you, please, provide an example with a reproduction.

Closed for now.

**Closed as completed** 2024-02-16 09:34 UTC
