### ISSUE TITLE
Tag search does not work anymore

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/nextcloud-vue#3662] opened 2023-01-17 08:10 UTC
Ref https://github.com/nextcloud/server/issues/36152

### Steps to reproduce

1. Create tags `test-1` until `test-10`
2. Go to any other place where tags can be selected (the tag management does not use the component yet), e.g. creating a workflow with automated tagging: https://github.com/nextcloud/files_automatedtagging
3. Search for `test-6` and try to pick it.

### Expected
Option is displayed

### Actual
The result list is empty

### Guess
The problem is that the custom filter is applied before the search:
https://github.com/nextcloud/nextcloud-vue/blob/4df172ae3869cec3733daa207308f6cf701aedbc/src/components/NcMultiselectTags/NcMultiselectTags.vue#L200-L205
https://github.com/nextcloud/nextcloud-vue/blob/84e7175ac2fd48c578187ae9de496ca3cbd498ac/src/components/NcSelectTags/NcSelectTags.vue#L261-L266

So we proceed with 5 items (default filter) into the search and then have no results left.

**Comment by nickvergessen** [comment] 2023-01-17 08:24
### Workaround
```js
:options-filter="() => true"
```
Can be used to remove the filter.

### Optimal solution
But of course it would be nice to have the filter apply after a potential search.

### Other solution

Another option would be to change the default filter to not filter when a search is performed if that would work:
```js
		optionsFilter: {
			type: Function,
			default: (_element, index) => index < 5 || this.search !== '',
		},
```

**Comment by PVince81** [comment] 2023-01-23 10:05
duplicate of https://github.com/nextcloud/server/issues/34395 ?

@Pytal

**Comment by nickvergessen** [comment] 2023-01-23 10:26
https://github.com/nextcloud/server/issues/36152 should be a duplicate of the server ticket.
Can keep one to remember the lib upgrade. But the vue repo ticket needs to stay :)

**Comment by Pytal** [comment] 2023-01-23 19:57
By previous design in https://github.com/nextcloud/nextcloud-vue/pull/2973 and https://github.com/nextcloud/nextcloud-vue/pull/2990

Since filtering is handled by the lib component, for NcSelectTags the best option is probably to use the https://vue-select.org/api/props.html#filter prop to truncate to 5 after the filtering logic

Should we do NcMultiselectTags as well @nickvergessen?

**Comment by nickvergessen** [comment] 2023-01-23 20:39
> Should we do NcMultiselectTags

Since it's deprecated we could also skip it and just ask to migrate to the new component.

**Comment by Pytal** [comment] 2023-02-14 00:11
Fixed in https://github.com/nextcloud/nextcloud-vue/pull/3747

**Closed** 2023-02-14 14:15 UTC
Labels: bug, 3. to review, feature: select/multiselect
