### ISSUE TITLE
Issues when importing some functions from NcRichText.js

### ISSUE THREAD

**Issue by julien-nc** [nextcloud/nextcloud-vue#3864] opened 2023-03-06 11:58 UTC
When importing `registerWidget`, `registerCustomPickerElement` or `NcCustomPickerRenderResult` from `@nextcloud/vue/dist/Components/NcRichText.js` the script fails and we get `Uncaught TypeError: inspect is undefined` in the browser console:

![image](https://user-images.githubusercontent.com/11291457/223099707-a188ec50-5d1c-40eb-b713-aa2f575ac1d6.png)

But this error goes away as soon as we import something from `@nextcloud/vue-richtext`, even an empty import like `import {} from '@nextcloud/vue-richtext'`.

This issue cannot be reproduced when linking with `@nextcloud/vue` (same with master or v7.8.0, it works fine).

So it seems there are some missing dependencies in the `@nextcloud/vue` package. Or can it be related with node-polyfill? I'm lost there.

To reproduce this bug, one can use this integration_tmdb branch: https://github.com/julien-nc/integration_tmdb/tree/enh/noid/replace-vue-richtext-by-vue , compile and enable the app in NC 26 or master and browse Talk or the Files app (with Text enabled).
The problematic import is in https://github.com/julien-nc/integration_tmdb/blob/enh/noid/replace-vue-richtext-by-vue/src/reference.js#L23-L24

cc @raimund-schluessler @juliushaertl

**Comment by raimund-schluessler** [comment] 2023-03-06 19:44
I went through the (dev)dependencies list of `vue-richtext` again, and found that these packages
```
"mdast-util-from-markdown": "^1.2.0",
"mdast-util-gfm-autolink-literal": "^1.0.2",
"mdast-util-to-string": "^3.1.0",
"micromark-extension-gfm-autolink-literal": "^1.0.3",
"remark-disable-tokenizers": "^1.1.0",
```
are not present in `nextcloud/vue` anymore. I didn't install them in #3841 because I thought that they were unused (I didn't find where they were imported/used).
Maybe it helps adding them?

It would probably help to know which package includes `inspect`. Would it work to compare the bundles produced with and w/o the import from `vue-richtext`?

**Comment by mejo-** [comment] 2023-03-08 14:57
@julien-nc I'm unable to reproduce this issue with either your branch of integration_tmdb and with collectives. I did the following:

- removed `@nextcloud/vue-richtext` from dependencies (completely gone from `package-lock.json`)
- upgraded to latest `@nextcloud/vue`
- used `import { registerWidget } from '@nextcloud/vue/dist/Components/NcRichText.js'`
- compiled the app
- tested using the smart picker and select elements found by the widget provided by collectives/integration_tmdb app

Anything I'm missing? :thinking:

**Comment by julien-nc** [comment] 2023-03-08 18:31
I've tried it with server stable26 and master in Talk and Text: not working.
I'm using npm v8.15.0 and node v16.17.0.
Weird indeed. What could be different between our contexts?

**Comment by juliushaertl** [comment] 2023-03-10 13:19
Just sharing the screenshot I took when checking this a bit with @julien-nc 

It was util -> console-browserify -> assert trying to call this

<img width="1552" alt="Screenshot 2023-03-06 at 21 50 26" src="https://user-images.githubusercontent.com/3404133/224325911-440f8ca1-e3c8-4ee9-b76d-4c15c4be7dab.png">

My first thought was that https://www.npmjs.com/package/node-polyfill-webpack-plugin was missing but adding didn't make any difference.

**Comment by juliushaertl** [comment] 2023-03-10 13:20
Also worth to mention that this doesn't happen in server with https://github.com/nextcloud/server/pull/33755

**Comment by juliushaertl** [comment] 2023-04-05 19:38
I could reproduce this locally with using `npm pack` instead of npm link, however have not really figured out what the difference is and why this doesn't work without the separate import.

Failing upstream lines in the trace
https://github.com/browserify/commonjs-assert/blob/master/internal/assert/assertion_error.js#L6
https://github.com/browserify/commonjs-assert/blob/master/internal/assert/assertion_error.js#L456

Steps to use npm pack
- in `@nextcloud/vue`: `npm ci && npm run dev && npm pack`
- Take the path to the freshly created tarball and add it to your apps package.json: `"@nextcloud/vue": "file:~/repos/nextcloud/@nextcloud/nextcloud-vue/nextcloud-vue-7.9.0.tgz",`
- In your app run `npm install && npm run dev`

**Comment by julien-nc** [comment] 2023-04-07 13:21
@ShGKme Hey, do you have any clue about that? Could it be caused by the webpack config in nextcloud/vue and how the package is built?

**Comment by ShGKme** [comment] 2023-04-15 00:55
Sooo. I could reproduce it and found the problem after some funny hours.

### Preface

1. Some libs are isomorph (for example, `axios`) and uses native Node modules (such as `util`, `process`)
2. In `@nextcloud/webpack-vue-config` we [polyfill](https://github.com/nextcloud/webpack-vue-config/blob/702973ab26f1b0007f528d3dcf685dc145bb0365/webpack.config.js#L111) all native "Node" modules with [node-polyfill-webpack-plugin](https://github.com/Richienb/node-polyfill-webpack-plugin)
3. All means **ALL**. Including, for example, `console`

### Why it fails

1. `NcRichText` depends on `util` native Node module polyfill
2. `util` polyfill depends on `console` polyfill ([link](https://github.com/browserify/node-util/blob/master/util.js))
3. `console` polyfill [depends](https://github.com/browserify/console-browserify/blob/f7eefc7c908c29d2e94954e5c6c1098e8c1028b4/index.js#L2-L3) on `util` and `assert` native node modules
4. 🎉 Congratulations: you have circular dependencies `util -> console -> util` 🔁
5. But the circular dependencies is not the problem. While module is in process of executing it already exists as an (empty) object. Dependencies can save the reference to this object.
6. `assert` polyfill [depends](https://github.com/browserify/commonjs-assert/blob/d932a53ae1b361f453050809878e4d8b7874d2a6/assert.js#L34) on `util` (more circular dependencies)
7. `assert` also **REQUIRES** `util` polyfill execution to be completed before. Because it uses not use a reference to the whole module object but takes a property from the module during evaluation 

```js
// 📁 browserify/commonjs-assert/assert.js
const { inspect } = require('util')
// While `util` is in process of evaluating, util = {}, inspect === undefined
// Later `util` will be evaluated. But `inspect` will remain undefined.
```


### Why it works

It is enough to evaluate `console` before `util` 🏆

1. `@nextcloud/vue-richtext` requires `@nextcloud/axois -> axios -> buffer polyfill -> console polyfill`
2. `console -> util -> console`. On this moment `util` is successfully polyfilled (having a reference to an empty `console` polyfill module).
3. `console -> assert -> util` now works, because `util` is already complete and cached 🥳

### How to solve the problem

`Console` should not be polyfilling. To archive that we need to exclude it from `node-polyfill-webpack-plugin`:

```diff
// 📁 webpack.config.js
const webpackConfig = {
  plugins: [
    // ... other plugins ...
-   new NodePolyfillPlugin()
+   new NodePolyfillPlugin({
+     excludeAliases: ['console']
+   })
    // ... other plugins ... 
  ]
}
```

Workaround for `integration_tmdb`:

```js
// 📁 webpack.js
// eslint-disable-next-line n/no-extraneous-require
const NodePolyfillPlugin = require('node-polyfill-webpack-plugin')
webpackConfig.plugins[1] = new NodePolyfillPlugin({
	excludeAliases: ['console'],
})
```

### Note

`Buffer` is also available in the browser and should not be polyfelt.

**Comment by ShGKme** [comment] 2023-04-17 15:24
> In other words: Could this be fixed by adjusting something in @nextcloud/vue or do you think fixing @nextcloud/webpack-vue-config is the only way to go?

It is not related to `@nextcloud/vue` because it is a problem with application bundling. It can be fixed either in a certain app or in `@nextcloud/webpack-vue-config`

**Comment by ShGKme** [comment] 2023-04-18 14:14
I'm closing the issue as it is not `@nextcloud/vue` issue

**Closed by ShGKme** 2023-04-18 14:14 UTC
Labels: bug, feature: richtext
